### ISSUE TITLE
Dependency on Kotlin serialization

### ISSUE THREAD

**Issue by eschoenawa** [Kynetics/uf-android-client#10]
In order to use the third party integration, an app is required to include `org.jetbrains.kotlinx:kotlinx-serialization-runtime` in their dependencies. This isn't mentioned in the documentation and normally the library should also come with such dependencies.

Here's a stacktrace you get when the dependency is missing:
```
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/serialization/json/Json;
        at com.kynetics.uf.android.api.UFServiceConfiguration.<clinit>(UFServiceConfiguration.kt:237)
        at java.lang.reflect.Field.getLong(Native Method)
        at java.io.ObjectStreamClass.getDeclaredSUID(ObjectStreamClass.java:1720)
        at java.io.ObjectStreamClass.access$700(ObjectStreamClass.java:72)
        at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:492)
        at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:480)
        at java.security.AccessController.doPrivileged(AccessController.java:43)
        at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:480)
        at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:377)
        at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:606)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1713)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1594)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1872)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1412)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
        at android.os.Parcel.readSerializable(Parcel.java:3134)
        at android.os.Parcel.readValue(Parcel.java:2917)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3244)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.BaseBundle.getSerializable(BaseBundle.java:1232)
        at android.os.Bundle.getSerializable(Bundle.java:1053)
        at com.kynetics.uf.android.api.CommunicationKt.toOutV1Message(Communication.kt:30)
        at com.example.updaterapp.MainActivity$IncomingHandler.handleMessage(MainActivity.kt:147)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1131)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.serialization.json.Json" on path: DexPathList[[zip file "/data/app/com.example.updaterapp-R-tSWp7Xo_Yf1YC1BEgB-g==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.updaterapp-R-tSWp7Xo_Yf1YC1BEgB-g==/lib/arm64, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.kynetics.uf.android.api.UFServiceConfiguration.<clinit>(UFServiceConfiguration.kt:237) 
        at java.lang.reflect.Field.getLong(Native Method) 
        at java.io.ObjectStreamClass.getDeclaredSUID(ObjectStreamClass.java:1720) 
        at java.io.ObjectStreamClass.access$700(ObjectStreamClass.java:72) 
        at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:492) 
        at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:480) 
        at java.security.AccessController.doPrivileged(AccessController.java:43) 
        at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:480) 
        at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:377) 
        at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:606) 
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1713) 
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1594) 
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1872) 
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1412) 
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427) 
        at android.os.Parcel.readSerializable(Parcel.java:3134) 
        at android.os.Parcel.readValue(Parcel.java:2917) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3244) 
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:236) 
        at android.os.BaseBundle.getSerializable(BaseBundle.java:1232) 
        at android.os.Bundle.getSerializable(Bundle.java:1053) 
        at com.kynetics.uf.android.api.CommunicationKt.toOutV1Message(Communication.kt:30) 
        at com.example.updaterapp.MainActivity$IncomingHandler.handleMessage(MainActivity.kt:147) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1131) 

```

**Comment by johnseremba** [comment]
If the project uses ProGuard, it is important to include kotlinx serialization ProGuard rules too. Otherwise, the obfuscated apk will always crash due to missing keep rules.
The rules used are;

```pro
# Kotlix Serialization
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.AnnotationsKt

# kotlinx-serialization-json specific.
-keepclassmembers class kotlinx.serialization.json.** {
    *** Companion;
}
-keepclasseswithmembers class kotlinx.serialization.json.** {
    kotlinx.serialization.KSerializer serializer(...);
}

-keep,includedescriptorclasses class com.kynetics.uf.android.api.**$$serializer { *; }
-keepclassmembers class  com.kynetics.uf.android.api.** {
    *** Companion;
}
-keepclasseswithmembers class com.kynetics.uf.android.api.** {
    kotlinx.serialization.KSerializer serializer(...);
}

```

**Comment by SaeedRe** [comment]
Proguard rules have been incorporated into the API.
https://github.com/Kynetics/uf-android-client/commit/80a54d9b16bd67e1f32a707230becb0947a9bcc0
