### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by bigcat26** [Kynetics/uf-android-client#4]
`> Task :uf-client-service:desugarReleaseFileDependencies
/Users/chris/.gradle/caches/transforms-2/files-2.1/0e79a2329e9dd4a923b95bfcf9b02b56/jetified-android.jar: D8: NullPointerException during IR Conversion

> Task :uf-client-service:desugarReleaseFileDependencies FAILED

FAILURE: Build failed with an exception.`

**Comment by diegorondini** [comment]
Hi,

thank you for reporting this issue.

Can you please provide the following details?

1. your build platform (Linux, Mac, ...)
2. Java version
3. build command you are using and full build log

Did you replace the android.jar as indicated in the README?
https://github.com/Kynetics/uf-android-client#build

**Comment by nicolalagloria** [comment]
Java 8 is recommended.

**Comment by bigcat26** [comment]
Hi @diegorondini @nicolalagloria thank you for reply.
1. I had tried build the project in Windows and Mac, used Android Studio and command line.
2. Java version: "1.8.0_271"
3. build command: `./gradlew assembleRelease`
4. I have placed the android.jar in `uf-android-client/uf-client-service/libs` folder

full build log with Android Studio:
```
Executing tasks: [:uf-client-service:assembleDebug] in project E:\code\uf-android-client

> Task :uf-client-service:preBuild UP-TO-DATE
> Task :uf-client-service:preDebugBuild UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:preBuild UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:preDebugBuild UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:compileDebugAidl NO-SOURCE
> Task :uf-client-service:uf-client-service-api:packageDebugRenderscript NO-SOURCE
> Task :uf-client-service:generateDebugBuildConfig UP-TO-DATE
> Task :uf-client-service:compileDebugAidl NO-SOURCE
> Task :uf-client-service:compileDebugRenderscript NO-SOURCE
> Task :uf-client-service:mainApkListPersistenceDebug UP-TO-DATE
> Task :uf-client-service:generateDebugResValues UP-TO-DATE
> Task :uf-client-service:generateDebugResources UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:generateDebugResValues UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:compileDebugRenderscript NO-SOURCE
> Task :uf-client-service:uf-client-service-api:generateDebugResources UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:packageDebugResources UP-TO-DATE
> Task :uf-client-service:mergeDebugResources UP-TO-DATE
> Task :uf-client-service:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :uf-client-service:extractDeepLinksDebug UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:extractDeepLinksDebug UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:processDebugManifest UP-TO-DATE
> Task :uf-client-service:processDebugManifest UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:compileDebugLibraryResources UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:parseDebugLocalResources UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:generateDebugRFile UP-TO-DATE
> Task :uf-client-service:processDebugResources UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:generateDebugBuildConfig UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:prepareLintJar UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:prepareLintJarForPublish UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:generateDebugSources UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:dataBindingExportBuildInfoDebug UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:dataBindingMergeDependencyArtifactsDebug UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:dataBindingMergeGenClassesDebug UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:dataBindingGenBaseClassesDebug UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:compileDebugKotlin UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:javaPreCompileDebug UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:compileDebugJavaWithJavac UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:bundleLibCompileDebug UP-TO-DATE
> Task :uf-client-service:compileDebugKotlin UP-TO-DATE
> Task :uf-client-service:javaPreCompileDebug UP-TO-DATE
> Task :uf-client-service:compileDebugJavaWithJavac UP-TO-DATE
> Task :uf-client-service:compileDebugSources UP-TO-DATE
> Task :uf-client-service:mergeDebugShaders UP-TO-DATE
> Task :uf-client-service:compileDebugShaders UP-TO-DATE
> Task :uf-client-service:generateDebugAssets UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:mergeDebugShaders UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:compileDebugShaders UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:generateDebugAssets UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:packageDebugAssets UP-TO-DATE
> Task :uf-client-service:mergeDebugAssets UP-TO-DATE
> Task :uf-client-service:processDebugJavaRes NO-SOURCE
> Task :uf-client-service:uf-client-service-api:processDebugJavaRes NO-SOURCE
> Task :uf-client-service:uf-client-service-api:bundleLibResDebug UP-TO-DATE
> Task :uf-client-service:mergeDebugJavaResource UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:bundleLibRuntimeDebug UP-TO-DATE
> Task :uf-client-service:checkDebugDuplicateClasses UP-TO-DATE
> Task :uf-client-service:dexBuilderDebug UP-TO-DATE
> Task :uf-client-service:mergeDebugJniLibFolders UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:mergeDebugJniLibFolders UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:mergeDebugNativeLibs UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:stripDebugDebugSymbols UP-TO-DATE
> Task :uf-client-service:uf-client-service-api:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :uf-client-service:mergeDebugNativeLibs UP-TO-DATE
> Task :uf-client-service:stripDebugDebugSymbols UP-TO-DATE
> Task :uf-client-service:validateSigningDebug UP-TO-DATE

> Task :uf-client-service:desugarDebugFileDependencies FAILED
AGPBI: {"kind":"error","text":"NullPointerException during IR Conversion","sources":[{"file":"C:\\Users\\Hsiung\\.gradle\\caches\\transforms-2\\files-2.1\\0e79a2329e9dd4a923b95bfcf9b02b56\\jetified-android.jar"}],"tool":"D8"}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':uf-client-service:desugarDebugFileDependencies'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Error while dexing.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
49 actionable tasks: 1 executed, 48 up-to-date
```

full build log in windows command line:

```
E:\code\uf-android-client>gradlew uf-client-service:assembleRelease --stacktrace

> Configure project :
org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: C:\Users\Hsiung\.gradle\daemon\5.6.4\.git
org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: C:\Users\Hsiung\.gradle\daemon\5.6.4\.git
org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: C:\Users\Hsiung\.gradle\daemon\5.6.4\.git

> Configure project :uf-client-service
org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: C:\Users\Hsiung\.gradle\daemon\5.6.4\.git

> Configure project :uf-client-ui-example
org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: C:\Users\Hsiung\.gradle\daemon\5.6.4\.git

> Configure project :uf-client-service:uf-client-service-api
org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: C:\Users\Hsiung\.gradle\daemon\5.6.4\.git

> Task :uf-client-service:uf-client-service-api:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':uf-client-service:uf-client-service-api:compileReleaseJavaWithJavac'.
> javax/xml/bind/JAXBException

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':uf-client-service:uf-client-service-api:compileReleaseJavaWithJavac'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.instantiateProcessor(AnnotationProcessingCompileTask.java:137)
        at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.setupProcessors(AnnotationProcessingCompileTask.java:109)
        at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.call(AnnotationProcessingCompileTask.java:92)
        at org.gradle.api.internal.tasks.compile.ResourceCleaningCompilationTask.call(ResourceCleaningCompilationTask.java:57)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:54)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:39)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:100)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:52)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
        at org.gradle.api.internal.tasks.compile.AnnotationProcessorDiscoveringCompiler.execute(AnnotationProcessorDiscoveringCompiler.java:51)
        at org.gradle.api.internal.tasks.compile.AnnotationProcessorDiscoveringCompiler.execute(AnnotationProcessorDiscoveringCompiler.java:37)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:39)
        at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilerFactory$2.execute(IncrementalCompilerFactory.java:101)
        at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilerFactory$2.execute(IncrementalCompilerFactory.java:97)
        at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringCompiler.execute(IncrementalResultStoringCompiler.java:60)
        at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringCompiler.execute(IncrementalResultStoringCompiler.java:44)
        at org.gradle.api.internal.tasks.compile.CompileJavaBuildOperationReportingCompiler$2.call(CompileJavaBuildOperationReportingCompiler.java:59)
        at org.gradle.api.internal.tasks.compile.CompileJavaBuildOperationReportingCompiler$2.call(CompileJavaBuildOperationReportingCompiler.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.compile.CompileJavaBuildOperationReportingCompiler.execute(CompileJavaBuildOperationReportingCompiler.java:51)
        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:158)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:126)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskInputsTaskAction.doExecute(IncrementalTaskInputsTaskAction.java:47)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
        at org.gradle.api.internal.project.taskfactory.AbstractIncrementalTaskAction.execute(AbstractIncrementalTaskAction.java:25)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$0(ExecuteStep.java:32)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:32)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
        ... 34 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        ... 118 more


* Get more help at https://help.gradle.org

BUILD FAILED in 6s
25 actionable tasks: 1 executed, 24 up-to-date
```

**Comment by diegorondini** [comment]
> Hi @diegorondini @nicolalagloria thank you for reply.
> <snip>
>     2. I have placed the android.jar in `uf-android-client/uf-client-service/libs` folder
> 

The `android.jar` needs to be replaced in the Android SDK files, as explained here:
https://github.com/anggrayudi/android-hidden-api#use-custom-androidjar
The exact jar to use is (rename to `.jar` after download):
https://github.com/anggrayudi/android-hidden-api/files/2709802/android.zip

Can you try again and let us know?

**Comment by bigcat26** [comment]
> > Hi @diegorondini @nicolalagloria thank you for reply.
> > 
> > 2. I have placed the android.jar in `uf-android-client/uf-client-service/libs` folder
> 
> The `android.jar` needs to be replaced in the Android SDK files, as explained here:
> https://github.com/anggrayudi/android-hidden-api#use-custom-androidjar
> The exact jar to use is (rename to `.jar` after download):
> https://github.com/anggrayudi/android-hidden-api/files/2709802/android.zip
> 
> Can you try again and let us know?

Thank you, it works.
After replaced the android.jar in Android SDK folder, the project was build successful with Android Studio.
Is there any side effects to replace the android.jar? It's smaller than the origin one.

**Comment by diegorondini** [comment]
> Is there any side effects to replace the android.jar? It's smaller than the origin one.

The whole android-hidden-api project is about accessing API not available in the standard SDK:
https://github.com/anggrayudi/android-hidden-api
